export enum ErrCode {
  VALIDATION = "VALIDATION_ERROR",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = "CONFLICT",
  RATE_LIMIT = "RATE_LIMITED",
  BAD_REQUEST = "BAD_REQUEST",
  INTERNAL = "INTERNAL_ERROR",
}
