// src/common/errors/error-codes.ts
export enum ErrCode {
  SUCCESS = "SUCCESS",
  BAD_REQUEST = "BAD_REQUEST",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = "CONFLICT",
  RATE_LIMIT = "RATE_LIMIT",
  VALIDATION = "VALIDATION",
  INTERNAL = "INTERNAL",
  DB_DUPLICATE = "DB_DUPLICATE",
  DB_FK = "DB_FOREIGN_KEY",
  DB_NOT_FOUND = "DB_NOT_FOUND",
}
