ALTER TYPE "TermPaymentRequestStatus" ADD VALUE IF NOT EXISTS 'SUBMITTED';
ALTER TYPE "TermPaymentRequestStatus" ADD VALUE IF NOT EXISTS 'IN_BATCH';
ALTER TYPE "TermPaymentRequestStatus" ADD VALUE IF NOT EXISTS 'SENT_TO_BANK';
ALTER TYPE "TermPaymentRequestStatus" ADD VALUE IF NOT EXISTS 'PARTIALLY_PAID';
ALTER TYPE "TermPaymentRequestStatus" ADD VALUE IF NOT EXISTS 'PAID';
