// src/common/auth/permissions.constant.ts
export const PERMISSIONS = {
    system: {
        rbacAdmin: 'system.rbac.admin',
    },
    contracts: {
        view: 'contracts.view',
        create: 'contracts.create',
        update: 'contracts.update',
        delete: 'contracts.delete',
        import: 'contracts.import',
    },
    customers: {
        view: 'customers.view',
        create: 'customers.create',
        update: 'customers.update',
        delete: 'customers.delete',
    },
    employees: {
        view: 'employees.view',
        create: 'employees.create',
        update: 'employees.update',
        delete: 'employees.delete',
    },
    users: {
        view: 'users.view',
        create: 'users.create',
        update: 'users.update',
        delete: 'users.delete',
        assignRoles: 'users.assign_roles',
        assignEmployee: 'users.assign_employee',
        resetPassword: 'users.reset_password',
    },
    roles: {
        view: 'roles.view',
        create: 'roles.create',
        update: 'roles.update',
        delete: 'roles.delete',
        assignPermissions: 'roles.assign_permissions',
    },
    departments: {
        view: 'departments.view',
        create: 'departments.create',
        update: 'departments.update',
        delete: 'departments.delete',
    },
    products: {
        view: 'products.view',
        create: 'products.create',
        update: 'products.update',
        delete: 'products.delete',
    },
    priceBulletins: {
        view: 'price_bulletins.view',
        create: 'price_bulletins.create',
        update: 'price_bulletins.update',
        delete: 'price_bulletins.delete',
        import: 'price_bulletins.import',
    },
    banking: {
        view: 'banking.view',
        create: 'banking.create',
        update: 'banking.update',
        delete: 'banking.delete',
    },
    purchases: {
        view: 'purchases.view',
        create: 'purchases.create',
        update: 'purchases.update',
        cancel: 'purchases.cancel',
        print: 'purchases.print',
        approve: 'purchases.approve',
        reject: 'purchases.reject',
    },
    sales: {
        view: 'sales.view',
        create: 'sales.create',
        update: 'sales.update',
        delete: 'sales.delete',
    },
} as const
