export const QB_SUPPLIER_INVOICE = 'qb-supplier-invoice'
export const JOB_SUPPLIER_INVOICE_PDF_PREVIEW = 'SUPPLIER_INVOICE_IMPORT_PDF'

export const ARTIFACT_PDF_INPUT = 'SUPPLIER_INVOICE_PDF_INPUT'
export const ARTIFACT_PDF_PREVIEW = 'SUPPLIER_INVOICE_PDF_PREVIEW'
